### ISSUE TITLE
Uncaught Error: Notification must be created with string message: Error: EEXIST: file already exi...

### ISSUE THREAD

**Issue by setalosas** [lohek/less-autocompile#57]
[Enter steps to reproduce:]

1. I just press ctrl-S and I get this window for a given .less file, always for the last hour. The output CSS is not updated. It worked until now, but of course I changed the file continuously. The file compiles OK with command line lessc.
2. The saving (and compiling) work with another file.

**Atom**: 1.20.0-beta4 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Pro Insider Preview
**Thrown From**: [less-autocompile](https://github.com/lohek/less-autocompile) package 1.0.0

### Stack Trace

Uncaught Error: Notification must be created with string message: Error: EEXIST: file already exists, mkdir 'C:\Users\chuck\Dropbox\custom\userscripts\u2b\u2b-macmag-fix.css'

```
At C:\Users\chuck\AppData\Local\atom\app-1.20.0-beta4\resources\app\src\notification.js:25

Error: Notification must be created with string message: Error: EEXIST: file already exists, mkdir 'C:\Users\chuck\Dropbox\custom\userscripts\u2b\u2b-macmag-fix.css'
    at Notification.module.exports.Notification.validate (~/AppData/Local/atom/app-1.20.0-beta4/resources/app/src/notification.js:25:21)
    at new Notification (~/AppData/Local/atom/app-1.20.0-beta4/resources/app/src/notification.js:20:18)
    at NotificationManager.module.exports.NotificationManager.addError (~/AppData/Local/atom/app-1.20.0-beta4/resources/app/src/notification-manager.js:41:41)
    at /packages/less-autocompile/lib/less-autocompile-view.coffee:59:28
    at /packages/flex-tool-bar/node_modules/mkdirp/index.js:47:53
    at FSReqWrap.oncomplete (fs.js:112:15)
```

### Commands

```
     -1:21.7.0 project-manager:list-projects (atom-pane.pane.active)
     -1:05.8.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-atom-material-syntax-light.theme-atom-material-ui)
  5x -0:46.8.0 core:move-down (input.hidden-input)
 17x -0:41.8.0 intentions:highlight (input.hidden-input)
     -0:40.8.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-live-server 2.1.2 
atom-material-syntax-light 0.4.6 
atom-material-ui 2.0.4 
atom-runner 2.7.1 
atom-solarized-dark-ui 0.28.1 
atom-terminal-panel 4.4.4 
atom-ternjs 0.18.3 
autoclose-html 0.23.0 
browser-plus 0.0.98 
busy-signal 1.4.3 
color-picker 2.2.5 
custom-title 1.0.1 
file-icons 2.1.9 
flex-tool-bar 0.12.0 
fonts 3.0.2 
glowing-cursor 0.1.2 
hyperclick 0.1.3 
icon-fonts 2.16.2 
intentions 1.1.5 
ionic-preview 0.7.0 
jekyll 2.1.0 
jslint 1.5.1 
less-autocompile 1.0.0 
linter 2.2.0 
linter-eslint 8.2.1 
linter-js-standard 3.9.3 
linter-jshint 3.1.5 
linter-php 1.3.2 
linter-ui-default 1.6.3 
material-syntax 0.6.1 
material-ui 1.0.10 
materialize-css 0.3.0 
minimap 4.29.3 
minimap-autohide 0.10.1 
minimap-bookmarks 0.4.2 
minimap-find-and-replace 4.5.2 
minimap-pigments 0.2.2 
multi-cursor-plus 1.2.0 
open-in-browser 0.5.2 
open-recent 5.0.0 
php-debug 0.2.4 
php-integrator-autocomplete-plus 1.6.0 
php-integrator-base 3.0.1 
php-integrator-navigation 1.2.1 
pigments 0.40.1 
platformio-ide-terminal 2.5.4 
pretty-json 1.6.4 
project-manager 3.3.5 
quick-highlight 0.10.0 
save-session 0.15.7 
select-rectangle 1.0.2 
solarized-dark-apparent-ui-successor 0.2.0 
solarized-dark-ui 0.3.2 
tool-bar 1.1.0 
tool-bar-main 0.0.10 
toolbar-iconshortcuts 3.13.0 
```
![image](https://user-images.githubusercontent.com/21111643/29816912-54a8f108-8cb6-11e7-863b-400430010fa2.png)

**Comment by setalosas** [comment]
If I make an error in the .less file, I get the proper error message for that, not the error message above, even if the error is in the last line of the css file.

If I correct it - I get back the Uncaught Error message.
